tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑"
    behind: "↓"
    staged: " "
    conflict: " "
    modified: " "
    untracked: " "
    stashed: "⚑"
    clean: "✔"
    insertions: " "
    deletions: " "
  styles:
    clear: "#[fg=#{@thm_fg}]"
    state: "#[fg=#{@thm_red},bold]"
    branch: "#[fg=#{@thm_mauve}]"
    remote: "#[fg=#{@thm_teal}]"
    divergence: "#[fg=#{@thm_overlay_1}]"
    staged: "#[fg=#{@thm_green}]"
    conflict: "#[fg=#{@thm_red},bold]"
    modified: "#[fg=#{@thm_yellow}]"
    untracked: "#[fg=#{@thm_overlay_1}]"
    stashed: "#[fg=#{@thm_blue}]"
    clean: "#[fg=#{@thm_green}]"
    insertions: "#[fg=#{@thm_green}]"
    deletions: "#[fg=#{@thm_red}]"
  layout:
    - branch
    - " "
    - divergence
    - " "
    - flags
    - " "
    - stats